// 1688 Products  - MythRealms
export type ProductImageRoles = {
  primary: string;
  alternate?: string;
  detail?: string;
  wearing?: string;
};

export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  categoryName: string;
  description: string;
  price: number;
  compareAt?: number;
  image: string;
  images: string[];
  imageRoles?: ProductImageRoles;
  tag?: string;
  isBestSeller: boolean;
  isNew: boolean;
  isActive: boolean;
  inStock: boolean;
  rating: number;
  reviewCount: number;
  intention?: string;
  benefitTriplet?: string;
}
export interface Category { name: string; slug: string; description: string; image?: string; }

export const CATEGORIES: Category[] = [
  { name: 'The Pearl Edit', slug: 'pearl-series', description: 'Luminous pearl jewelry for everyday light, texture, and quiet confidence.', image: '/images/collections/collections封面1.webp' },
];
const SOURCE_PRODUCTS: Product[] = [

  // ===== THE SERENITY COLLECTION  - Pearl Series (20 SKUs) =====
  { id:'1688-011', name:'The Gentle Tide - Bracelet', slug:'pearl-series-11', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Gentleness is not weakness. It is discipline  - the discipline of not hardening when the world asks you to, of choosing softness again and again on purpose. This pearl bracelet is for those who stay tender in a world that rewards toughness. Wear it as a daily vote for gentleness  - yours, and everyone else\'s.', price:44.99, image:'/images/products/1688-shop/pearl-series/pearl-series-11-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-11-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-11-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-11-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-11-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-11-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.5, reviewCount:20 },
  { id:'1688-004', name:'The Deep Peace - Bracelet & Necklace Set', slug:'pearl-series-04', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Two pearls. Two placements. One intention: peace that goes all the way down  - past the surface, past the performance, into the place where you are just yourself. Wear the bracelet on your left wrist  - the receiving side. Wear the necklace close to your heart. This is not jewelry. This is a daily practice of returning to calm.', price:69.99, compareAt:89.99, image:'/images/products/1688-shop/pearl-series/pearl-series-04-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-04-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-04-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-04-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-04-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-04-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.8, reviewCount:13 },
  { id:'1688-015', name:'The Water\'s Edge - Earrings', slug:'pearl-series-15', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'At the edge of the water, everything is possible. Nothing has been decided yet. Nothing is too late. These pearl earrings live in that space  - the threshold between what was and what comes next, the pause before the plunge. For the ones standing at the edge, toes in the surf, ready to wade in.', price:39.99, image:'/images/products/1688-shop/pearl-series/pearl-series-15-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-15-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-15-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-15-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-15-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-15-detail4.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.9, reviewCount:24 },
  { id:'1688-019', name:'The Light Keeper - Necklace', slug:'pearl-series-19', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Every circle needs someone who tends the fire  - who stays up late, who checks in, who makes sure everyone got home safe. You are that someone. This pearl necklace is for the light keepers. The ones who hold space. The ones who remember. Wear it when you need to be tended back  - when the keeper needs a keeper.', price:54.99, image:'/images/products/1688-shop/pearl-series/pearl-series-19-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-19-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-19-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-19-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-19-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-19-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.8, reviewCount:28 },
  { id:'1688-001', name:'The Calm Tide - Ring', slug:'pearl-series-01', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'When the world is loud, this is your stillness. Freshwater pearl  - the stone of emotional balance, worn for centuries by those who sought the centre of the storm. Hold your ring each morning. Name one thing you are releasing. One thing you are inviting. Put it on. Wear the quiet.', price:29.99, compareAt:39.99, image:'/images/products/1688-shop/pearl-series/pearl-series-01-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-01-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-01-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-01-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-01-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-01-detail4.webp"], tag:'Low Stock', isBestSeller:true, isNew:true, isActive:true, inStock:true, rating:4.5, reviewCount:10 },
  { id:'1688-002', name:'The Still Point - Ring', slug:'pearl-series-02', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'There is a place inside you that nothing can touch. This pearl ring is a reminder to return there. Saltwater pearl with natural iridescence  - no two alike, each one a quiet declaration of presence. Wear it on your dominant hand. Let every glance remind you: you are the still point in a turning world.', price:32.99, image:'/images/products/1688-shop/pearl-series/pearl-series-02-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-02-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-02-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-02-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-02-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-02-detail4.webp"], tag:'Bestseller', isBestSeller:true, isNew:true, isActive:true, inStock:true, rating:4.6, reviewCount:11 },
  { id:'1688-003', name:'The Quiet Centre - Ring', slug:'pearl-series-03', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Not every power announces itself. Some wait in the hush between heartbeats. This is the pearl for those who lead from within  - quietly, steadily, without needing to be seen leading. Freshwater pearl, hand-selected for its depth of luster. Wear it daily. When the noise rises, touch the pearl. Come back to centre.', price:34.99, image:'/images/products/1688-shop/pearl-series/pearl-series-03-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-03-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-03-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-03-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-03-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-03-detail4.webp"], tag:'Bestseller', isBestSeller:true, isNew:true, isActive:true, inStock:true, rating:4.7, reviewCount:12 },
  { id:'1688-005', name:'The First Light - Bracelet', slug:'pearl-series-05', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Before the noise begins, there is a moment. The pearl catches light. You remember who you are  - before the inbox, before the demands, before the world asks anything of you. Freshwater pearl bracelet, luminous and new. Put it on first thing in the morning, before you check your phone. Let it set the tone for everything that follows.', price:32.99, image:'/images/products/1688-shop/pearl-series/pearl-series-05-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-05-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-05-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-05-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-05-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-05-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.9, reviewCount:14 },
  { id:'1688-006', name:'The Inner Tide - Bracelet', slug:'pearl-series-06', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'You are tidal. You rise. You recede. You return  - and every phase has its own kind of beauty. This bracelet is for the ebb and flow, a reminder that no state is permanent and every season has its gift. Saltwater pearl, luminous and layered. Wear it through your moods. It keeps your rhythm when you forget you have one.', price:34.99, image:'/images/products/1688-shop/pearl-series/pearl-series-06-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-06-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-06-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-06-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-06-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-06-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.5, reviewCount:15 },
  { id:'1688-007', name:'The Silver Hour - Bracelet', slug:'pearl-series-07', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'There is an hour  - usually late, often alone  - when the light turns silver and everything softens. This is the pearl for that hour. Freshwater pearl with cool silver undertones, elegant and understated. Wear it to dinner. Wear it alone with a book. Wear it when you need to feel like yourself again.', price:36.99, image:'/images/products/1688-shop/pearl-series/pearl-series-07-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-07-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-07-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-07-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-07-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-07-detail4.webp", "/images/products/1688-shop/pearl-series/pearl-series-07-detail5.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.6, reviewCount:16 },
  { id:'1688-008', name:'The Clear Blue - Bracelet', slug:'pearl-series-08', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Clarity wears a pearl. Not the clarity of having all the answers  - the clarity of knowing you do not need them all at once. Freshwater pearl with cool blue undertones, hand-strung on elastic cord. Wear it when you are weighing a decision. Let it remind you that calm water reflects best  - and the clearest thinking comes from the stillest mind.', price:38.99, image:'/images/products/1688-shop/pearl-series/pearl-series-08-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-08-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-08-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-08-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-08-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-08-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.7, reviewCount:17 },
  { id:'1688-009', name:'The Keeper - Bracelet', slug:'pearl-series-09', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Some people hold things. Appointments. Birthdays. The one thing everyone else forgot. This pearl is for the keepers  - the ones who carry tissues and remember names and never drop a thread. Freshwater pearl, strong and luminous, built for daily wear. You take care of everyone. Let this one take care of you.', price:40.99, compareAt:52.99, image:'/images/products/1688-shop/pearl-series/pearl-series-09-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-09-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-09-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-09-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-09-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-09-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.8, reviewCount:18 },
  { id:'1688-010', name:'The Steady Light - Bracelet', slug:'pearl-series-10', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Not a blaze. Not a flicker. A steady, quiet glow that does not need to prove anything to anyone. This is the pearl that matches your light  - the one that has been burning longer than you remember, the one that other people notice even when you do not. Freshwater pearl, hand-strung. Wear it every day. Let it be the one thing you never take off.', price:42.99, image:'/images/products/1688-shop/pearl-series/pearl-series-10-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-10-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-10-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-10-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-10-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-10-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.9, reviewCount:19 },
  { id:'1688-012', name:'The Horizon Line - Bracelet', slug:'pearl-series-12', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Where the sky meets the sea  - always there, always changing, never the same twice. This bracelet is for those who hold both at once: the known and the unknown, the settled and the becoming, who you have been and who you are about to be. Freshwater pearl with horizon-colored iridescence. Wear it through the transition.', price:46.99, image:'/images/products/1688-shop/pearl-series/pearl-series-12-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-12-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-12-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-12-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-12-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-12-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.6, reviewCount:21 },
  { id:'1688-013', name:'The Soft Return - Earrings', slug:'pearl-series-13', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'After the long day. After the hard conversation. After the version of you that the world required all afternoon. You come home. You take off your earrings. And you are still you  - soft, whole, unperformed. These pearl drops are for the soft return, the moment you remember yourself after hours of being everyone else.', price:34.99, image:'/images/products/1688-shop/pearl-series/pearl-series-13-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-13-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-13-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-13-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-13-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-13-detail4.webp", "/images/products/1688-shop/pearl-series/pearl-series-13-detail5.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.7, reviewCount:22 },
  { id:'1688-014', name:'The Morning Pearl - Earrings', slug:'pearl-series-14', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Put them on before coffee. Before the first notification. Before the world asks anything of you  - while the day still belongs entirely to you. These are morning pearls, for the hour when you are still just yours and nothing has been decided yet. Wear them as a boundary. Beauty first. Demands later.', price:37.99, image:'/images/products/1688-shop/pearl-series/pearl-series-14-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-14-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-14-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-14-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-14-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-14-detail4.webp", "/images/products/1688-shop/pearl-series/pearl-series-14-detail5.webp", "/images/products/1688-shop/pearl-series/pearl-series-14-detail6.webp", "/images/products/1688-shop/pearl-series/pearl-series-14-detail7.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.8, reviewCount:23 },
  { id:'1688-016', name:'The Listening Stone - Earrings', slug:'pearl-series-16', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Most people wear jewelry to be seen. You wear these to listen better  - to catch what others miss: the pause, the glance, the thing left unsaid in the space between words. Pearls for the listeners. For the ones who hear what is not being spoken. Wear them when someone needs to be truly heard.', price:42.99, compareAt:54.99, image:'/images/products/1688-shop/pearl-series/pearl-series-16-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-16-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-16-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-16-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-16-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-16-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.5, reviewCount:25 },
  { id:'1688-017', name:'The Inner Glow - Necklace', slug:'pearl-series-17', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Some light comes from within. It does not need a source. It does not need to be explained or justified. This pearl necklace carries that light  - luminous against the skin, visible only to those who look closely, unmistakable to those who know what they are seeing. Wear it close to your heart. The light is already there.', price:42.99, image:'/images/products/1688-shop/pearl-series/pearl-series-17-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-17-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-17-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-17-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-17-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-17-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.6, reviewCount:26 },
  { id:'1688-018', name:'The Open Gate - Necklace', slug:'pearl-series-18', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'A gate that opens inward. A necklace that rests at the threshold  - the place where who you were meets who you are becoming. This pearl piece is for moments of crossing: new jobs, new love, new versions of yourself that you have not quite met yet. Wear it through the doorway. Let it be the first thing you put on in your new life.', price:49.99, compareAt:64.99, image:'/images/products/1688-shop/pearl-series/pearl-series-18-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-18-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-18-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-18-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-18-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-18-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.7, reviewCount:27 },
  { id:'1688-020', name:'The Deep Breath - Necklace', slug:'pearl-series-20', category:'pearl-series', categoryName:'The Serenity Collection', intention:'Emotional Balance', benefitTriplet:'Calm  - Wisdom  - Peace', description:'Before you say the thing. Before you make the call. Before you walk into the room where everything changes. One deep breath. This pearl rests at the breath line  - a reminder to pause, to fill your lungs, to arrive fully before you speak. Freshwater pearl, hand-knotted. The pause is the practice. The breath is the beginning.', price:59.99, image:'/images/products/1688-shop/pearl-series/pearl-series-20-main.webp', images:["/images/products/1688-shop/pearl-series/pearl-series-20-main.webp", "/images/products/1688-shop/pearl-series/pearl-series-20-detail1.webp", "/images/products/1688-shop/pearl-series/pearl-series-20-detail2.webp", "/images/products/1688-shop/pearl-series/pearl-series-20-detail3.webp", "/images/products/1688-shop/pearl-series/pearl-series-20-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.9, reviewCount:29 },

  // ===== THE INTENTION STONES  - Luxe Collection (12 SKUs) =====
  { id:'1688-021', name:'The Watchman - Bracelet', slug:'luxe-collection-01', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Protection', benefitTriplet:'Protection  - Grounding  - Clarity', description:'You carry more than anyone knows. The Watchman is for those who guard  - their energy, their peace, their invisible perimeter. Dark stone of protection, hand-strung on elastic cord. Hold it each morning. Set your boundary. Nothing enters unless you permit it. Wear it daily. This is not jewelry. This is armor you chose.', price:42.99, compareAt:54.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-01-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-01-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-01-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-01-detail2.webp"], tag:'Bestseller', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.5, reviewCount:30 },
  { id:'1688-027', name:'The Lion\'s Share - Bracelet', slug:'luxe-collection-07', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Abundance', benefitTriplet:'Luck  - Opportunity  - Prosperity', description:'Abundance is not a number. It is not a threshold you cross once and stay across. It is a posture  - the daily willingness to receive what is already yours, to say yes more than you say no, to keep your hands open when the instinct is to close them. The Lion\'s Share is green stone of prosperity. Wear it with open hands. The receiving is the practice.', price:49.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-07-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-07-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-07-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-07-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-07-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-07-detail4.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.6, reviewCount:36 },
  { id:'1688-023', name:'The Seer - Bracelet', slug:'luxe-collection-03', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Intuition', benefitTriplet:'Calm  - Vision  - Connection', description:'You already know the answer. You have known it for a while. You just have not trusted yourself enough to act on it. The Seer is for the ones who sense what others miss  - violet stone of intuition and inner sight. Wear it when you need to hear your own voice over the noise of everyone else\'s opinions. Wear it to bed. Let it work while you sleep.', price:46.99, compareAt:59.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-03-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-03-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-03-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-03-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-03-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-03-detail4.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-03-detail5.webp"], tag:'Bestseller', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.7, reviewCount:32 },
  { id:'1688-024', name:'The Strategist - Bracelet', slug:'luxe-collection-04', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Confidence', benefitTriplet:'Focus  - Courage  - Will', description:'Confidence is not loud. It is not the biggest voice in the room. It is the quiet decision to trust yourself before the evidence shows up  - to act while others are still waiting for permission. The Strategist is the stone of steady nerve and clear action. Wear it into the meeting. Wear it onto the stage. Wear it when the moment asks for your best self.', price:48.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-04-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-04-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-04-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-04-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-04-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-04-detail4.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.8, reviewCount:33 },
  { id:'1688-025', name:'The Phoenix - Bracelet', slug:'luxe-collection-05', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Renewal', benefitTriplet:'Renewal  - Intuition  - Feminine Power', description:'You have burned down and rebuilt more times than anyone knows. You have ended things. You have walked away. You have stood in the ashes and decided  - again  - to become. The Phoenix is the stone of new moons and clean slates and the courage to begin again before you feel ready. Put it on after the ending. Wear it into the beginning.', price:49.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-05-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-05-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-05-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-05-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-05-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-05-detail4.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.9, reviewCount:34 },
  { id:'1688-026', name:'The Creator - Bracelet', slug:'luxe-collection-06', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Manifestation', benefitTriplet:'Clarity  - Amplification  - Purpose', description:'Everything that exists began as a thought someone took seriously. The Creator is the stone for the ones who make things real  - who turn ideas into objects, visions into plans, intentions into outcomes. Clear stone of pure purpose. Hold it. Name what you are making. Picture it done. Put it on. Then do the work that brings it into being.', price:52.99, compareAt:68.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-06-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-06-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-06-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-06-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-06-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-06-detail4.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-06-detail5.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.5, reviewCount:35 },
  { id:'1688-022', name:'The Heart Opener - Bracelet', slug:'luxe-collection-02', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Self-Love', benefitTriplet:'Love  - Healing  - Softness', description:'This is the stone for when you are learning to let people in again  - or learning to let yourself be enough, without anyone else\'s permission. Rose-colored, soft, but not fragile. The Heart Opener does not make you vulnerable. It makes you brave. Wear it on your left wrist, the receiving side. Let it teach you that softness is a form of strength.', price:44.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-02-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-02-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-02-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-02-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-02-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-02-detail4.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-02-detail5.webp"], tag:'Low Stock', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.6, reviewCount:31 },
  { id:'1688-028', name:'The Anchor - Earrings', slug:'luxe-collection-08', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Grounding', benefitTriplet:'Stability  - Presence  - Calm', description:'Some days you float away  - scattered by notifications, fragmented by demands, pulled in six directions by people who need pieces of you. These earrings bring you back. The Anchor is for the overthinkers, the spiralers, the people whose feet forget the ground is still there. Wear them when you need to feel the earth under you again.', price:44.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-08-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-08-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-08-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-08-detail2.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.7, reviewCount:37 },
  { id:'1688-029', name:'The Muse - Earrings', slug:'luxe-collection-09', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Creativity', benefitTriplet:'Inspiration  - Flow  - Expression', description:'Creativity does not visit the waiting. It comes to the ones already working  - already moving, already making, already deep in the mess of becoming. The Muse is for the makers who do not wait for permission or perfect conditions. Wear them in the studio. At the desk. In the darkroom. The work summons the muse  - not the other way around.', price:47.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-09-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-09-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-09-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-09-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-09-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-09-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.8, reviewCount:38 },
  { id:'1688-030', name:'The Sage - Earrings', slug:'luxe-collection-10', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Wisdom', benefitTriplet:'Discernment  - Depth  - Clarity', description:'Wisdom is not knowing more than other people. It is knowing what matters and letting the rest go without a fight  - choosing your battles, guarding your attention, saving your energy for what actually counts. The Sage is deep blue stone of discernment. Wear these when you need to choose between two goods, or when you need to say no to something that looks like yes.', price:49.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-10-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-10-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-10-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-10-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-10-detail3.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.9, reviewCount:39 },
  { id:'1688-031', name:'The North Star - Earrings', slug:'luxe-collection-11', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Direction', benefitTriplet:'Guidance  - Purpose  - Conviction', description:'When you do not know which way to go  - when every path looks the same and every option feels wrong  - you need a fixed point. Something that does not move while everything else spins. The North Star is for moments of crossing: career changes, hard decisions, the vertigo of too many choices. Let these earrings be the thing that stays still.', price:52.99, compareAt:68.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-11-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-11-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-11-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-11-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-11-detail3.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.5, reviewCount:40 },
  { id:'1688-032', name:'The Lightkeeper - Necklace', slug:'luxe-collection-12', category:'luxe-collection', categoryName:'The Intention Stones', intention:'Clarity', benefitTriplet:'Illumination  - Truth  - Vision', description:'Some people illuminate rooms. Some people illuminate other people  - they walk in and suddenly you can see your own thoughts more clearly. The Lightkeeper is for the ones who see clearly and speak truly. Stone of morning light and clear water. Wear it close to your throat. Let your words be clean. Let your presence light the room.', price:64.99, image:'/images/products/1688-shop/luxe-collection/luxe-collection-12-main.webp', images:["/images/products/1688-shop/luxe-collection/luxe-collection-12-main.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-12-detail1.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-12-detail2.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-12-detail3.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-12-detail4.webp", "/images/products/1688-shop/luxe-collection/luxe-collection-12-detail5.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.6, reviewCount:41 },

  // ===== BALANCE & LIGHT  - Pearl & Crystal (4 SKUs) =====
  { id:'1688-033', name:'The Bridge - Bracelet', slug:'pearl-crystal-series-01', category:'pearl-crystal-series', categoryName:'Balance & Light', intention:'Transition', benefitTriplet:'Harmony  - Elevation  - Renewal', description:'Between who you were and who you are becoming, there is a bridge  - and you are standing in the middle of it right now. This bracelet spans both sides: pearl on one end, crystal on the other, stillness and light held in balance. Wear it during transitions  - career shifts, relationship evolutions, the quiet becoming that happens when no one is looking. You are not lost. You are crossing.', price:38.99, image:'/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-01-main.webp', images:["/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-01-main.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-01-detail1.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-01-detail2.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-01-detail3.webp"], tag:'Bestseller', isBestSeller:true, isNew:true, isActive:true, inStock:true, rating:4.7, reviewCount:42 },
  { id:'1688-034', name:'The Threshold - Bracelet', slug:'pearl-crystal-series-02', category:'pearl-crystal-series', categoryName:'Balance & Light', intention:'Transformation', benefitTriplet:'Harmony  - Elevation  - Renewal', description:'Every doorway asks a question: are you ready to become someone new? The Threshold is for the moment before the step  - the pause that makes the movement meaningful, the breath before the decision, the stillness that precedes everything worth doing. Pearl and crystal, soft and sharp, quiet and bright. Wear it when you are about to cross over and you need one thing to hold.', price:42.99, image:'/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-main.webp', images:["/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-main.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-detail1.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-detail2.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-detail3.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-detail4.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-detail5.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-02-detail6.webp"], tag:'Low Stock', isBestSeller:true, isNew:true, isActive:true, inStock:true, rating:4.8, reviewCount:43 },
  { id:'1688-035', name:'The Double Knot - Bracelet', slug:'pearl-crystal-series-03', category:'pearl-crystal-series', categoryName:'Balance & Light', intention:'Integration', benefitTriplet:'Harmony  - Elevation  - Renewal', description:'Two stones. Two intentions. One wrist. The Double Knot is for those who live in the both-and  - soft and strong, rooted and reaching, quiet and fierce, the one who stayed and the one who finally left. You do not have to choose between your selves. You get to be all of them. Wear this bracelet as proof that opposites do not cancel  - they complete.', price:44.99, compareAt:56.99, image:'/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-main.webp', images:["/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-main.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-detail1.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-detail2.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-detail3.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-detail4.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-detail5.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-03-detail6.webp"], tag:'Bestseller', isBestSeller:true, isNew:true, isActive:true, inStock:true, rating:4.9, reviewCount:44 },
  { id:'1688-036', name:'The Keeper of Light - Bracelet', slug:'pearl-crystal-series-04', category:'pearl-crystal-series', categoryName:'Balance & Light', intention:'Self-Sourcing', benefitTriplet:'Harmony  - Elevation  - Renewal', description:'Some people carry light for others  - they show up, they hold space, they make everyone feel seen. But who carries light for you? This bracelet is the answer: you do. Pearl and crystal in balance, the glow and the gleam, the soft and the sharp. Wear it as a reminder that you are your own light source. You always were.', price:46.99, image:'/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-04-main.webp', images:["/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-04-main.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-04-detail1.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-04-detail2.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-04-detail3.webp", "/images/products/1688-shop/pearl-crystal-series/pearl-crystal-series-04-detail4.webp"], tag:'New', isBestSeller:false, isNew:true, isActive:true, inStock:true, rating:4.5, reviewCount:45 },

  // ===== THE ARCHETYPES  - Curated Singles (6 SKUs) =====
  { id:'1688-037', name:'The Watchman - Bracelet', slug:'curated-singles-01', category:'curated-singles', categoryName:'The Archetypes', intention:'Protection', benefitTriplet:'Protection  - Grounding  - Clarity', description:'The Watchman is a black obsidian crystal bracelet designed for protection and grounding. Black obsidian is a volcanic glass used for centuries as a protective stone  - it absorbs negative energy and returns only strength. Hand-strung on elastic cord. One size fits most. Hold it each morning. Set your perimeter. Nothing enters unless you permit it. This is not jewelry. This is armor you chose. Protection  - Grounding  - Clarity.', price:44.99, compareAt:57.99, image:'/images/products/1688-shop/curated-singles/curated-singles-01-main.webp', images:["/images/products/1688-shop/curated-singles/curated-singles-01-main.webp", "/images/products/1688-shop/curated-singles/curated-singles-01-detail1.webp", "/images/products/1688-shop/curated-singles/curated-singles-01-detail2.webp", "/images/products/1688-shop/curated-singles/curated-singles-01-detail3.webp"], tag:'Bestseller', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.6, reviewCount:46 },
  { id:'1688-038', name:'The Heart Opener - Bracelet', slug:'curated-singles-02', category:'curated-singles', categoryName:'The Archetypes', intention:'Self-Love', benefitTriplet:'Love  - Healing  - Softness', description:'The Heart Opener is a rose quartz crystal bracelet designed for self-love and emotional healing. Rose quartz has been called the stone of unconditional love for centuries  - it opens the heart inward and quiets the inner critic. Hand-strung on elastic cord. One size fits most. Wear it on your left wrist, the receiving side. Let it teach you that softness is a form of strength. Love  - Healing  - Softness.', price:47.99, image:'/images/products/1688-shop/curated-singles/curated-singles-02-main.webp', images:["/images/products/1688-shop/curated-singles/curated-singles-02-main.webp", "/images/products/1688-shop/curated-singles/curated-singles-02-detail1.webp", "/images/products/1688-shop/curated-singles/curated-singles-02-detail2.webp", "/images/products/1688-shop/curated-singles/curated-singles-02-detail3.webp", "/images/products/1688-shop/curated-singles/curated-singles-02-detail4.webp"], tag:'Low Stock', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.7, reviewCount:47 },
  { id:'1688-039', name:'The Seer - Bracelet', slug:'curated-singles-03', category:'curated-singles', categoryName:'The Archetypes', intention:'Intuition', benefitTriplet:'Calm  - Vision  - Connection', description:'The Seer is an amethyst crystal bracelet designed for intuition and mental clarity. Amethyst has been valued for centuries as a stone of the third eye  - it quiets mental noise and helps you hear your own voice. Hand-strung on elastic cord. One size fits most. Wear it to bed. Let it work while you sleep. When you wake, trust what you already knew. Calm  - Vision  - Connection.', price:49.99, compareAt:64.99, image:'/images/products/1688-shop/curated-singles/curated-singles-03-main.webp', images:["/images/products/1688-shop/curated-singles/curated-singles-03-main.webp", "/images/products/1688-shop/curated-singles/curated-singles-03-detail1.webp", "/images/products/1688-shop/curated-singles/curated-singles-03-detail2.webp", "/images/products/1688-shop/curated-singles/curated-singles-03-detail3.webp", "/images/products/1688-shop/curated-singles/curated-singles-03-detail4.webp", "/images/products/1688-shop/curated-singles/curated-singles-03-detail5.webp", "/images/products/1688-shop/curated-singles/curated-singles-03-detail6.webp"], tag:'Bestseller', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.8, reviewCount:48 },
  { id:'1688-040', name:'The Phoenix - Bracelet', slug:'curated-singles-04', category:'curated-singles', categoryName:'The Archetypes', intention:'Renewal', benefitTriplet:'Renewal  - Intuition  - Feminine Power', description:'The Phoenix is a moonstone crystal bracelet designed for new beginnings and renewal. Moonstone has been associated with new moons and fresh starts for centuries  - it carries the energy of transformation and the courage to begin again. Hand-strung on elastic cord. One size fits most. Put it on after the ending. Wear it into the beginning. Renewal  - Intuition  - Feminine Power.', price:52.99, image:'/images/products/1688-shop/curated-singles/curated-singles-04-main.webp', images:["/images/products/1688-shop/curated-singles/curated-singles-04-main.webp", "/images/products/1688-shop/curated-singles/curated-singles-04-detail1.webp", "/images/products/1688-shop/curated-singles/curated-singles-04-detail2.webp", "/images/products/1688-shop/curated-singles/curated-singles-04-detail3.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.9, reviewCount:49 },
  { id:'1688-041', name:'The Strategist - Bracelet', slug:'curated-singles-05', category:'curated-singles', categoryName:'The Archetypes', intention:'Confidence', benefitTriplet:'Focus  - Courage  - Will', description:'The Strategist is a tiger\'s eye crystal bracelet designed for confidence and focus. Tiger\'s eye has been used for centuries as a stone of courage and clear thinking  - its chatoyant golden bands are said to sharpen the mind and steady the nerves. Hand-strung on elastic cord. One size fits most. Wear it into the meeting. Wear it onto the stage. Wear it when you need to be the version of yourself that acts. Focus  - Courage  - Will.', price:52.99, image:'/images/products/1688-shop/curated-singles/curated-singles-05-main.webp', images:["/images/products/1688-shop/curated-singles/curated-singles-05-main.webp", "/images/products/1688-shop/curated-singles/curated-singles-05-detail1.webp", "/images/products/1688-shop/curated-singles/curated-singles-05-detail2.webp", "/images/products/1688-shop/curated-singles/curated-singles-05-detail3.webp", "/images/products/1688-shop/curated-singles/curated-singles-05-detail4.webp", "/images/products/1688-shop/curated-singles/curated-singles-05-detail5.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.5, reviewCount:10 },
  { id:'1688-042', name:'The Lion\'s Share - Bracelet', slug:'curated-singles-06', category:'curated-singles', categoryName:'The Archetypes', intention:'Abundance', benefitTriplet:'Luck  - Opportunity  - Prosperity', description:'The Lion\'s Share is a green aventurine crystal bracelet designed for abundance and prosperity. Green aventurine has been called the stone of opportunity for centuries  - it is believed to attract luck and help you receive what is already yours. Hand-strung on elastic cord. One size fits most. Wear it with open hands. Say yes more than you say no. Luck  - Opportunity  - Prosperity.', price:54.99, compareAt:69.99, image:'/images/products/1688-shop/curated-singles/curated-singles-06-main.webp', images:["/images/products/1688-shop/curated-singles/curated-singles-06-main.webp", "/images/products/1688-shop/curated-singles/curated-singles-06-detail1.webp", "/images/products/1688-shop/curated-singles/curated-singles-06-detail2.webp", "/images/products/1688-shop/curated-singles/curated-singles-06-detail3.webp", "/images/products/1688-shop/curated-singles/curated-singles-06-detail4.webp"], tag:'New', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:4.6, reviewCount:11 },

  // ===== TEST PRODUCT =====
  { id:'1688-099', name:'Test Product - PayPal Test', slug:'test-product', category:'curated-singles', categoryName:'The Archetypes', intention:'Testing', benefitTriplet:'Test - Verify - Confirm', description:'This is a $1 test product to verify the PayPal payment flow. Delete after testing.', price:1.00, image:'/images/products/1688-shop/curated-singles/curated-singles-01-main.webp', images:["/images/products/1688-shop/curated-singles/curated-singles-01-main.webp"], tag:'Test', isBestSeller:false, isNew:false, isActive:false, inStock:true, rating:5.0, reviewCount:1 },
];

function pearlProductKind(name: string): string {
  const normalized = name.toLowerCase();
  if (normalized.includes("set")) return "jewelry set";
  if (normalized.includes("ring")) return "ring";
  if (normalized.includes("earring")) return "earring design";
  if (normalized.includes("necklace")) return "necklace";
  return "bracelet";
}

const pearlSourceImage = (slug: string, view: "main" | `detail${number}`) =>
  `/images/products/1688-shop/pearl-series/${slug}-${view}.webp`;

const sourceGallery = (
  slug: string,
  alternateView: `detail${number}`,
  detailView: `detail${number}`,
): [string, string, string] => [
  pearlSourceImage(slug, "main"),
  pearlSourceImage(slug, alternateView),
  pearlSourceImage(slug, detailView),
];

// Every active product gallery uses an exact supplier source file. The order is
// main product view, alternate supplier view, then product detail. No AI
// reconstruction is used, so the material, structure, and proportions stay intact.
const SOURCE_PRESERVED_PRODUCT_IMAGES: Record<string, [string, string, string]> = {
  "pearl-series-01": sourceGallery("pearl-series-01", "detail3", "detail1"),
  "pearl-series-02": sourceGallery("pearl-series-02", "detail2", "detail1"),
  "pearl-series-03": sourceGallery("pearl-series-03", "detail2", "detail1"),
  "pearl-series-04": sourceGallery("pearl-series-04", "detail3", "detail1"),
  "pearl-series-05": sourceGallery("pearl-series-05", "detail3", "detail1"),
  "pearl-series-06": sourceGallery("pearl-series-06", "detail3", "detail1"),
  "pearl-series-07": sourceGallery("pearl-series-07", "detail4", "detail1"),
  "pearl-series-08": sourceGallery("pearl-series-08", "detail3", "detail1"),
  "pearl-series-09": sourceGallery("pearl-series-09", "detail3", "detail1"),
  "pearl-series-10": sourceGallery("pearl-series-10", "detail3", "detail1"),
  "pearl-series-11": sourceGallery("pearl-series-11", "detail3", "detail1"),
  "pearl-series-12": sourceGallery("pearl-series-12", "detail3", "detail1"),
  "pearl-series-13": sourceGallery("pearl-series-13", "detail4", "detail1"),
  "pearl-series-14": sourceGallery("pearl-series-14", "detail5", "detail1"),
  "pearl-series-15": sourceGallery("pearl-series-15", "detail2", "detail1"),
  "pearl-series-16": sourceGallery("pearl-series-16", "detail2", "detail1"),
  "pearl-series-17": sourceGallery("pearl-series-17", "detail3", "detail1"),
  "pearl-series-18": sourceGallery("pearl-series-18", "detail1", "detail2"),
  "pearl-series-19": sourceGallery("pearl-series-19", "detail3", "detail1"),
  "pearl-series-20": sourceGallery("pearl-series-20", "detail3", "detail1"),
};

// This approved pilot is intentionally limited to one product. Its source
// gallery remains in public/images as a non-destructive fallback.
const EDITORIAL_PILOT_IMAGES: Record<
  string,
  [string, string, string, string, string]
> = {
  "pearl-series-01": [
    "/images/products/1688-shop/pearl-series/pearl-series-01-editorial-v1-01-hero.png",
    "/images/products/1688-shop/pearl-series/pearl-series-01-editorial-v1-02-macro.png",
    "/images/products/1688-shop/pearl-series/pearl-series-01-editorial-v1-03-worn.png",
    "/images/products/1688-shop/pearl-series/pearl-series-01-editorial-v1-04-profile.png",
    "/images/products/1688-shop/pearl-series/pearl-series-01-editorial-v1-05-atmosphere.png",
  ],
};

const EDITORIAL_CORE_SLUGS = [
  "pearl-series-02", "pearl-series-03", "pearl-series-04", "pearl-series-05",
  "pearl-series-06", "pearl-series-07", "pearl-series-08", "pearl-series-09",
  "pearl-series-10", "pearl-series-11", "pearl-series-12", "pearl-series-13",
  "pearl-series-14", "pearl-series-15", "pearl-series-16", "pearl-series-17",
  "pearl-series-18", "pearl-series-19", "pearl-series-20",
] as const;

const EDITORIAL_CORE_IMAGES = Object.fromEntries(
  EDITORIAL_CORE_SLUGS.map((slug) => [
    slug,
    [
      `/images/products/1688-shop/pearl-series/${slug}-editorial-v1-01-hero.png`,
      `/images/products/1688-shop/pearl-series/${slug}-editorial-v1-02-macro.png`,
      `/images/products/1688-shop/pearl-series/${slug}-editorial-v1-03-worn.png`,
    ],
  ]),
) as Record<string, [string, string, string]>;

export const PRODUCTS: Product[] = SOURCE_PRODUCTS.map((sourceProduct) => {
  const product: Product = {
    ...sourceProduct,
    images: [...sourceProduct.images],
    isActive: sourceProduct.category === "pearl-series",
  };
  if (!product.isActive) return product;

  if (product.slug === "pearl-series-16") {
    product.name = "The Listening Pearl - Earrings";
  }
  const kind = pearlProductKind(product.name);
  const images = SOURCE_PRESERVED_PRODUCT_IMAGES[product.slug];
  product.categoryName = "The Pearl Edit";
  product.intention = "Everyday Pearl";
  product.benefitTriplet = "Pearl - Light - Everyday";
  product.description = `${product.name} is a pearl ${kind} from The Pearl Edit. It is presented for everyday styling and occasion dressing. Review the product gallery for the exact shape, setting, scale, and finish; lighting and screens can affect how details appear.`;
  product.rating = 0;
  product.reviewCount = 0;
  product.isBestSeller = false;
  product.tag = product.isNew ? "New" : undefined;
  const editorialImages = EDITORIAL_PILOT_IMAGES[product.slug];
  if (editorialImages) {
    const [primary, detail, wearing] = editorialImages;
    product.image = primary;
    product.images = [...editorialImages];
    product.imageRoles = { primary, wearing, detail };
  } else if (EDITORIAL_CORE_IMAGES[product.slug]) {
    const [primary, detail, wearing] = EDITORIAL_CORE_IMAGES[product.slug];
    product.image = primary;
    product.images = [primary, detail, wearing];
    product.imageRoles = { primary, detail, wearing };
  } else if (images) {
    const [primary, alternate, detail] = images;
    product.image = primary;
    product.images = [...images];
    product.imageRoles = {
      primary,
      alternate,
      detail,
    };
  }
  return product;
});

export function getProductBySlug(s:string):Product|undefined{return PRODUCTS.find(p=>p.slug===s&&p.isActive&&p.inStock)}
export function getProductsByCategory(c:string):Product[]{return PRODUCTS.filter(p=>p.category===c&&p.isActive&&p.inStock)}
export function getBestSellers(l=8):Product[]{return PRODUCTS.filter(p=>p.isBestSeller&&p.isActive&&p.inStock).slice(0,l)}
export function getNewArrivals(l=8):Product[]{return PRODUCTS.filter(p=>p.isNew&&p.isActive&&p.inStock).slice(0,l)}
