import type { Product } from "@/lib/1688-products";

type NewSeriesProductInput = {
  id: string;
  slug: string;
  name: string;
  kind:
    | "earring design"
    | "bracelet"
    | "necklace"
    | "eyewear chain"
    | "hair accessory";
  price: number;
  detailCount: number;
  description: string;
};

function sourceGallery(slug: string, detailCount: number): string[] {
  const root = `/images/products/new-series/${slug}`;
  return [
    `${root}/main.jpg`,
    ...Array.from(
      { length: detailCount },
      (_, index) => `${root}/detail-${String(index + 1).padStart(2, "0")}.jpg`,
    ),
  ];
}

function createProduct(input: NewSeriesProductInput): Product {
  const sourceImages = sourceGallery(input.slug, input.detailCount);
  const editorialImages = [
    "new-series-white-shell-flower-drops", "new-series-gold-shell-teardrops",
    "new-series-baroque-pearl-hoops", "new-series-purple-gem-pearl-drops",
    "new-series-white-petal-flower-earrings", "new-series-mother-of-pearl-cluster-earrings",
    "new-series-white-shell-triple-drops", "new-series-round-shell-disc-drops",
    "new-series-pearl-jade-bracelet", "new-series-purple-gem-bangle",
    "new-series-shell-twist-pearl-cuff", "new-series-leaf-turquoise-pearl-cuff",
    "new-series-leaf-pearl-bracelet", "new-series-round-shell-gold-cuff",
    "new-series-purple-stone-pendant-necklace", "new-series-pearl-y-lariat",
    "new-series-green-layered-pendant-necklace", "new-series-pearl-dreamcatcher-lariat",
    "new-series-pearl-drop-choker", "new-series-multi-strand-pearl-choker",
    "new-series-black-drop-pearl-choker", "new-series-pearl-glasses-chain",
    "new-series-shell-drop-glasses-chain", "new-series-classic-pearl-chain",
    "new-series-turquoise-bead-chain",
    "new-series-white-floral-hair-stick", "new-series-white-flower-wood-stick",
    "new-series-pearl-cluster-hair-claw", "new-series-gold-pearl-hair-stick",
    "new-series-pearl-flower-u-pin", "new-series-pearl-bar-hair-clip",
    "new-series-shell-chip-hair-clip", "new-series-wood-flower-hair-stick",
    "new-series-daisy-chain-hair-stick", "new-series-wood-pearl-hair-stick",
    "new-series-gold-star-hair-stick", "new-series-star-flower-hair-clip",
    "new-series-chain-flower-hair-pin", "new-series-flower-pearl-hair-clip",
    "new-series-pink-flower-hair-clip", "new-series-blue-flower-bow-hair-clip",
    "new-series-blue-teardrop-hair-stick", "new-series-dragonfly-hair-clip",
  ].includes(input.slug)
    ? [
        `/images/products/new-series/${input.slug}/editorial-v1-01-hero.png`,
        `/images/products/new-series/${input.slug}/editorial-v1-02-macro.png`,
        `/images/products/new-series/${input.slug}/editorial-v1-03-worn.png`,
      ]
    : undefined;
  const images = editorialImages ?? sourceImages;
  const productType = input.kind === "earring design" ? "earrings" : input.kind;

  return {
    id: input.id,
    slug: input.slug,
    name: input.name,
    category: "pearl-series",
    categoryName: "The Pearl Edit",
    description: input.description,
    price: input.price,
    image: images[0],
    images,
    imageRoles: {
      primary: images[0],
      ...(images[1] ? { detail: images[1] } : {}),
      ...(images[2] ? { wearing: images[2] } : {}),
    },
    tag: "New",
    isBestSeller: false,
    isNew: true,
    isActive: true,
    inStock: true,
    rating: 0,
    reviewCount: 0,
    intention: `Pearl ${productType}`,
    benefitTriplet: "Pearl - Detail - Everyday",
  };
}

export const NEW_SERIES_PRODUCTS: Product[] = [
  createProduct({
    id: "new-series-001",
    slug: "new-series-white-shell-flower-drops",
    name: "The Dewflower - Earrings",
    kind: "earring design",
    price: 34.99,
    detailCount: 4,
    description: "The Dewflower - Earrings show translucent white flower drops with scalloped petals, small rounded accents, and warm gold-toned links at the top. Seen flat, the two flowers form an airy pair. Worn, the lower petals create a soft vertical line near the face. An ivory blouse keeps the pale colors quiet, while loose hair lets the floral outline remain visible.",
  }),
  createProduct({
    id: "new-series-002",
    slug: "new-series-gold-shell-teardrops",
    name: "The Golden Petal - Earrings",
    kind: "earring design",
    price: 39.99,
    detailCount: 4,
    description: "The Golden Petal - Earrings place a pale petal-shaped center inside a warm gold-toned oval edged with small cream beads. Their teardrop outline gives the front view a neat oval rhythm, with a brighter rim around the softer center. A dark neckline makes the light center easier to read; a clean knit keeps the look simple.",
  }),
  createProduct({
    id: "new-series-003",
    slug: "new-series-baroque-pearl-hoops",
    name: "The Baroque Orbit - Earrings",
    kind: "earring design",
    price: 44.99,
    detailCount: 6,
    description: "The Baroque Orbit - Earrings set irregular luminous white drops beside smooth round hoops in warm gold-toned color. The curved hoops and uneven lower shapes create two different rhythms in one pair, so the silhouette reads organic in the close-up; pull hair behind the ears for an open view, or place the earrings against a crisp collar.",
  }),
  createProduct({
    id: "new-series-004",
    slug: "new-series-purple-gem-pearl-drops",
    name: "The Violet Rain - Earrings",
    kind: "earring design",
    price: 42.99,
    detailCount: 4,
    description: "The Violet Rain - Earrings combine a milky oval center with a saturated violet border and small reflective points around the edge. A round violet stud repeats the upper color. Together, the stud and drop read from top to bottom rather than as a single disc. Cream, black, or a muted lilac top gives the purple frame space.",
  }),
  createProduct({
    id: "new-series-005",
    slug: "new-series-white-petal-flower-earrings",
    name: "The White Garden - Earrings",
    kind: "earring design",
    price: 39.99,
    detailCount: 4,
    description: "The White Garden - Earrings use four rounded white petals around a small luminous bead, with each flower kept close to the ear. The soft translucence and simple symmetry give the pair a fresh floral outline without extra hanging parts. With hair gathered low, the petal shape stays open; a darker blouse supplies contrast.",
  }),
  createProduct({
    id: "new-series-006",
    slug: "new-series-mother-of-pearl-cluster-earrings",
    name: "The Shell Bloom - Earrings",
    kind: "earring design",
    price: 44.99,
    detailCount: 5,
    description: "The Shell Bloom - Earrings gather layered pale petal forms, a small bead grouping, and a round lower charm into a clustered drop. Overlapping shapes make the pair feel full in the gallery, while the open spaces between petals keep the outline legible; let them sit beside a plain neckline, or use a black top to frame the pale cluster.",
  }),
  createProduct({
    id: "new-series-007",
    slug: "new-series-white-shell-triple-drops",
    name: "The Triple Light - Earrings",
    kind: "earring design",
    price: 42.99,
    detailCount: 4,
    description: "The Triple Light - Earrings line up three pale round shell-like discs, each framed by a warm gold-toned edge and joined in a vertical drop. The repeated circles make the length easy to follow, while the slightly pearly surfaces keep the color soft. A swept-back hairstyle shows the line clearly; denim brings a casual blue counterpoint.",
  }),
  createProduct({
    id: "new-series-008",
    slug: "new-series-round-shell-disc-drops",
    name: "The Moon Disc - Earrings",
    kind: "earring design",
    price: 46.99,
    detailCount: 8,
    description: "The Moon Disc - Earrings use dark green-gray upper discs, softly iridescent lower discs, and small pale bead clusters at the joins. Color changes across the round surfaces create the impression of moonlit layers. The outline stays round and easy to follow; neutral clothing lets the green and blush tones show, while a printed scarf can echo either shade.",
  }),
  createProduct({
    id: "new-series-009",
    slug: "new-series-pearl-jade-bracelet",
    name: "The Green Current - Bracelet",
    kind: "bracelet",
    price: 44.99,
    detailCount: 4,
    description: "The Green Current - Bracelet follows irregular pearl-like white beads to a smooth green oval accent, with warm gold-toned links joining the sections. At the wrist, the green center interrupts the pale rhythm and gives the bracelet a clear place to look first; a rolled sleeve keeps the oval visible, while a plain chain can sit nearby without competing.",
  }),
  createProduct({
    id: "new-series-010",
    slug: "new-series-purple-gem-bangle",
    name: "The Violet Arc - Bracelet",
    kind: "bracelet",
    price: 49.99,
    detailCount: 5,
    description: "The Violet Arc - Bracelet places a faceted purple center between pale round accents on an open warm gold-toned bangle. Straight rails hold the shape apart from the faceted color, giving the wrist a simple arc with one concentrated point; it can sit over a neutral cuff, or a violet scarf can repeat the central color.",
  }),
  createProduct({
    id: "new-series-011",
    slug: "new-series-shell-twist-pearl-cuff",
    name: "The Shell Twist - Bracelet",
    kind: "bracelet",
    price: 46.99,
    detailCount: 5,
    description: "The Shell Twist - Bracelet circles smooth pale round forms and one irregular shell-like accent with a visibly coiled gold-toned line. The winding texture changes along the cuff, contrasting with the quiet, rounded centers. A short sleeve reveals the open arc; a simple watch creates a measured mix of textures.",
  }),
  createProduct({
    id: "new-series-012",
    slug: "new-series-leaf-turquoise-pearl-cuff",
    name: "The Turquoise Leaf - Bracelet",
    kind: "bracelet",
    price: 48.99,
    detailCount: 2,
    description: "The Turquoise Leaf - Bracelet brings turquoise-colored round accents and a pale irregular center into a looping gold-toned cuff whose middle sweep resembles a leaf. Blue-green color sits at both sides of the pale center, creating a balanced visual path around the wrist. The pale middle breaks up the cool color; cream or denim clothing keeps it legible, and nearby jewelry can stay minimal.",
  }),
  createProduct({
    id: "new-series-013",
    slug: "new-series-leaf-pearl-bracelet",
    name: "The Leaf Line - Bracelet",
    kind: "bracelet",
    price: 49.99,
    detailCount: 4,
    description: "The Leaf Line - Bracelet alternates pearl-like white beads with open leaf-shaped gold-toned forms in a repeating wrist line. Each leaf outline leaves a little space around the rounded accents, giving the bracelet a drawn, botanical appearance in the image. A flowing blouse follows the plant-like rhythm; a tailored jacket provides a sharper counterpoint.",
  }),
  createProduct({
    id: "new-series-014",
    slug: "new-series-round-shell-gold-cuff",
    name: "The Golden Shell - Bracelet",
    kind: "bracelet",
    price: 54.99,
    detailCount: 6,
    description: "The Golden Shell - Bracelet moves pale bead accents through several leaf- and shell-shaped gold-toned forms, then closes the rhythm with more rounded centers. The repeating motifs look like a small botanical sketch crossing the wrist rather than a plain row of beads. Ivory and sand clothing keep the palette together; a short sleeve gives the pattern room.",
  }),
  createProduct({
    id: "new-series-015",
    slug: "new-series-purple-stone-pendant-necklace",
    name: "The Violet Pendant - Necklace",
    kind: "necklace",
    price: 54.99,
    detailCount: 5,
    description: "The Violet Pendant - Necklace centers a faceted purple stone-like shape inside a rounded gold-toned frame and places it beneath a strand of dark, mauve, and smoky beads. Ornate connectors break up the bead line and draw attention toward the pendant's center. A crew neck leaves the pendant unobstructed; a muted purple accessory can continue the color story.",
  }),
  createProduct({
    id: "new-series-016",
    slug: "new-series-pearl-y-lariat",
    name: "The Falling Pearl - Lariat",
    kind: "necklace",
    price: 59.99,
    detailCount: 2,
    description: "The Falling Pearl - Lariat descends from a fine gold-toned chain through graduated pearl-like beads, an openwork center, and a final round drop. Its Y-shaped layout leaves the upper neckline quiet while the lower drop supplies the vertical emphasis; a scoop neck shows the full path, and an open blazer lets the last bead appear between the lapels.",
  }),
  createProduct({
    id: "new-series-017",
    slug: "new-series-green-layered-pendant-necklace",
    name: "The Green Layer - Necklace",
    kind: "necklace",
    price: 56.99,
    detailCount: 1,
    description: "The Green Layer - Necklace pairs a fine gold-toned chain with alternating light cream rounded beads, an openwork center, and a long pendant drop. The upper line stays spare. At the center, the pale forms gather into a narrow Y shape and release into a single lower bead. For a title-inspired green note, try sage, olive, or soft green clothing.",
  }),
  createProduct({
    id: "new-series-018",
    slug: "new-series-pearl-dreamcatcher-lariat",
    name: "The Dreamcatcher Pearl - Lariat",
    kind: "necklace",
    price: 62.99,
    detailCount: 1,
    description: "The Dreamcatcher Pearl - Lariat keeps its chain fine at the shoulders, collects pearl-like beads around a small openwork medallion, and finishes with a long central drop. A small oval frame gives the middle a defined pause before the hanging beads continue downward. An open shirt leaves the medallion visible; a V-neck follows the line of the lariat.",
  }),
  createProduct({
    id: "new-series-019",
    slug: "new-series-pearl-drop-choker",
    name: "The Pearl Drop - Choker",
    kind: "necklace",
    price: 57.99,
    detailCount: 3,
    description: "The Pearl Drop - Choker closes around the neck with a row of small pearl-like beads and sends several slim chain drops down from the front. Different drop lengths create a fringe edge that can be read as a narrow line or a wider fan, depending on the angle; a plain collar keeps the fringe visible, while a dark top makes the pale beads stand apart.",
  }),
  createProduct({
    id: "new-series-020",
    slug: "new-series-multi-strand-pearl-choker",
    name: "The Pearl Cascade - Choker",
    kind: "necklace",
    price: 64.99,
    detailCount: 2,
    description: "The Pearl Cascade - Choker combines a fine gold-toned chain with many strands of pearl-like beads that fall at varied lengths across the front. The cascading lines create movement below the close neckline. Repeated pale points keep the whole design visually connected; an open or square neckline frames the strands, and small earrings leave the layered front unobstructed.",
  }),
  createProduct({
    id: "new-series-021",
    slug: "new-series-black-drop-pearl-choker",
    name: "The Midnight Drop - Choker",
    kind: "necklace",
    price: 59.99,
    detailCount: 1,
    description: "The Midnight Drop - Choker is shown as a pale close-set bead line with fine gold-toned chains dropping into a pointed front fringe. Against a black or charcoal top, the light beads take on the night-time contrast suggested by the name, while the image's own palette stays pale and warm. A simple neckline keeps the descending chain lengths easy to see.",
  }),
  createProduct({
    id: "new-series-022",
    slug: "new-series-pearl-glasses-chain",
    name: "The Pearl Line - Eyewear Chain",
    kind: "eyewear chain",
    price: 34.99,
    detailCount: 4,
    description: "The Pearl Line - Eyewear Chain places rounded pearl-like beads at intervals along a fine gold-toned chain, ending in clear loops for glasses. The beaded sections sit near the frames and the quieter chain extends toward the shoulders, giving the accessory a long, open shape; clear, silver, or dark frames each create a different contrast, so choose the one that suits the rest of the outfit.",
  }),
  createProduct({
    id: "new-series-023",
    slug: "new-series-shell-drop-glasses-chain",
    name: "The Shell Drop - Eyewear Chain",
    kind: "eyewear chain",
    price: 36.99,
    detailCount: 2,
    description: "The Shell Drop - Eyewear Chain hangs a small fan-shaped shell-like pendant from each side of a slim gold-toned chain, with clear loops at the ends. Scalloped edges make the pale pendants easy to spot while the long line remains visually light. Light frames blend with the pendants; darker sunglasses make the shell-like shapes more apparent.",
  }),
  createProduct({
    id: "new-series-024",
    slug: "new-series-classic-pearl-chain",
    name: "The Classic Pearl - Eyewear Chain",
    kind: "eyewear chain",
    price: 32.99,
    detailCount: 0,
    description: "The Classic Pearl - Eyewear Chain keeps its front section quiet with evenly spaced pearl-like beads, then continues as a slim gold-toned line to clear glasses loops. The restrained rhythm can rest behind the neck or fall along the shoulders without taking over the frames. An everyday optical pair suits the simple line; a structured blazer gives it a cleaner backdrop.",
  }),
  createProduct({
    id: "new-series-025",
    slug: "new-series-turquoise-bead-chain",
    name: "The Turquoise Note - Eyewear Chain",
    kind: "eyewear chain",
    price: 34.99,
    detailCount: 0,
    description: "The Turquoise Note - Eyewear Chain interrupts its fine gold-toned line with two vertical groups of irregular turquoise-colored beads and clear loops for glasses. The blue-green sections appear near the shoulders when worn, making the chain read as a small color accent rather than an all-over strand. Neutral frames keep the turquoise visible; denim repeats the cool note.",
  }),
  createProduct({
    id: "new-series-026",
    slug: "new-series-white-floral-hair-stick",
    name: "The Blueheart Bloom - Hair Stick",
    kind: "hair accessory",
    price: 36.99,
    detailCount: 0,
    description: "The Blueheart Bloom - Hair Stick sets a white many-petaled flower on a slim gold-toned stick and places a cool blue-green round center at its heart. The long straight line contrasts with the irregular petal edges, giving an updo one clear horizontal-to-vertical transition. Through a low twist, both parts remain visible; a cool-toned blouse can echo the center.",
  }),
  createProduct({
    id: "new-series-027",
    slug: "new-series-white-flower-wood-stick",
    name: "The Ivory Woodflower - Hair Stick",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Ivory Woodflower - Hair Stick pairs a dark wood-toned curved stick with a small white flower and one pearl-like hanging accent. Brown and ivory create the main contrast, while the drop gives the side of an updo a small moving point; a loose bun leaves the curve visible, and cream and brown layers keep the palette close.",
  }),
  createProduct({
    id: "new-series-028",
    slug: "new-series-pearl-cluster-hair-claw",
    name: "The Pearl Cluster - Hair Claw",
    kind: "hair accessory",
    price: 42.99,
    detailCount: 0,
    description: "The Pearl Cluster - Hair Claw gathers irregular white pearl-like forms into a dense flower-like top over a visible gold-toned claw base. Rounded and petal-shaped pieces overlap around the center, so the upper section carries most of the visual weight. For a low twist, the cluster has a clear place to sit; a plain hair tie keeps the rest quiet.",
  }),
  createProduct({
    id: "new-series-029",
    slug: "new-series-gold-pearl-hair-stick",
    name: "The Golden Pearl - Hair Stick",
    kind: "hair accessory",
    price: 34.99,
    detailCount: 0,
    description: "The Golden Pearl - Hair Stick uses a long, slim gold-toned stick topped with one elongated pearl-like accent and a small open floral connector. Its straight body leaves the upper ornament as the only rounded focus, creating a simple line through an updo. Smoothly pinned hair shows the silhouette; softly gathered hair adds a less formal setting.",
  }),
  createProduct({
    id: "new-series-030",
    slug: "new-series-pearl-flower-u-pin",
    name: "The Pearl Halo - U Pin",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Pearl Halo - U Pin frames a five-petal flower and rounded pearl-like center with a circular ring of small pale accents, then extends into two long prongs. The open center leaves negative space around the flower, while the prongs continue the vertical direction into the hairstyle. Against a bun or braid, the halo has a clear backdrop; a plain neckline keeps attention above the shoulders.",
  }),
  createProduct({
    id: "new-series-031",
    slug: "new-series-pearl-bar-hair-clip",
    name: "The Triple Bloom - Hair Clip",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Triple Bloom - Hair Clip arranges three flower-like clusters across a gold-toned bar, using pale rounded forms and a warmer center in the middle bloom. Read from the side, it behaves like a short floral band; read from the front, the three centers create an easy rhythm. Place it beside a low ponytail, or let a simple side sweep expose the full bar.",
  }),
  createProduct({
    id: "new-series-032",
    slug: "new-series-shell-chip-hair-clip",
    name: "The Shell Petal - Hair Clip",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Shell Petal - Hair Clip sets irregular pale shell-like pieces and small rounded bead accents over an open gold-toned filigree base. Uneven petal shapes give the clip its gathered outline, while the filigree background keeps gaps visible between the pieces. A half-up style shows the whole arrangement; a pale blouse continues the shell-like color.",
  }),
  createProduct({
    id: "new-series-033",
    slug: "new-series-wood-flower-hair-stick",
    name: "The Woodflower Pearl - Hair Stick",
    kind: "hair accessory",
    price: 37.99,
    detailCount: 0,
    description: "The Woodflower Pearl - Hair Stick uses a dark wood-toned stick, two small floral ornaments, and one pale drop hanging from the upper section. The long brown base is visually quiet beside the light flowers, so the ornament reads as a botanical detail rather than a full headpiece. Within a low bun, the curved line stays easy to follow; denim or warm neutrals echo the base.",
  }),
  createProduct({
    id: "new-series-034",
    slug: "new-series-daisy-chain-hair-stick",
    name: "The Daisy Chain - Hair Stick",
    kind: "hair accessory",
    price: 36.99,
    detailCount: 0,
    description: "The Daisy Chain - Hair Stick centers a pale daisy-like flower with a bright yellow middle, pearl-like petal forms, and two trailing gold-toned chains. The stick gives the floral head a straight counterline, while the two chains extend the shape into motion beside the updo. A braid or loose bun gives the chains room; cream, yellow, or denim clothing picks up the visible colors.",
  }),
  createProduct({
    id: "new-series-035",
    slug: "new-series-wood-pearl-hair-stick",
    name: "The Cloud Pearl - Hair Stick",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Cloud Pearl - Hair Stick has a dark openwork top, a long narrow stick, and three pearl-like drops suspended from separate gold-toned chains. Cut-out spaces keep the upper shape legible, and the hanging drops create a small cluster beside the hair rather than across it. A twisted bun presents the full length; soft neutral clothing keeps the contrast clear.",
  }),
  createProduct({
    id: "new-series-036",
    slug: "new-series-gold-star-hair-stick",
    name: "The Amber Bloom - U Pin",
    kind: "hair accessory",
    price: 41.99,
    detailCount: 0,
    description: "The Amber Bloom - U Pin combines a white five-petal flower, an amber-colored center, branch-like details, and a long double-prong base. The bright center sits inside the pale petals like a small sun, while the open prongs leave the lower half visually spare. For a bun or chignon, the pin has a clear frame; a warm scarf can repeat the amber note.",
  }),
  createProduct({
    id: "new-series-037",
    slug: "new-series-star-flower-hair-clip",
    name: "The Pink Pearl Star - Hair Clip",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Pink Pearl Star - Hair Clip puts a pale pointed flower on a gold-toned bar, with a soft pink rounded center and small bright accents around it. Pointed petals make the outline crisp in the gallery, while the center brings a warmer spot into the otherwise pale arrangement. From a side sweep, the star shape stays open; cream, navy, or washed denim sets the pink against a darker field.",
  }),
  createProduct({
    id: "new-series-038",
    slug: "new-series-chain-flower-hair-pin",
    name: "The Pearl Canopy - U Pin",
    kind: "hair accessory",
    price: 44.99,
    detailCount: 0,
    description: "The Pearl Canopy - U Pin places a small rounded cluster inside an open rectangular frame and suspends several fine gold-toned chains below it. Fixed beads and moving lines share the same vertical path, giving the piece a canopy-like shape for an updo. A braid can hold the frame near the crown; a clean neckline leaves the chains visible.",
  }),
  createProduct({
    id: "new-series-039",
    slug: "new-series-flower-pearl-hair-clip",
    name: "The Pearl Moth - Hair Clip",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Pearl Moth - Hair Clip uses a warm gold-toned bar beneath an organic cluster of pale irregular forms, including one darker rounded accent at the center. The wing-like spread suggests a moth shape through its silhouette, while the mixed surfaces keep the close-up varied. Pin it near a temple or low twist; a dark top makes the pale forms easier to read.",
  }),
  createProduct({
    id: "new-series-040",
    slug: "new-series-pink-flower-hair-clip",
    name: "The Blush Cluster - Hair Clip",
    kind: "hair accessory",
    price: 36.99,
    detailCount: 0,
    description: "The Blush Cluster - Hair Clip gathers soft pink and white rounded forms into a compact floral group on a slim gold-toned clip. Its small footprint concentrates the color in one place, which lets a simple hairstyle remain the background. Above one ear or beside a ponytail, it adds a gentle blush note; cream and warm beige keep that note visible.",
  }),
  createProduct({
    id: "new-series-041",
    slug: "new-series-blue-flower-bow-hair-clip",
    name: "The Sea Glass Bloom - Hair Clip",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Sea Glass Bloom - Hair Clip centers a cool blue-green round accent inside pale petal-like forms on a warm gold-toned bar. The watery center and light petals make a clear cool-warm contrast, while the bar gives the cluster a firm horizontal base. In a side sweep or half-up style, the bloom stays in view; denim or a cool knit echoes the center.",
  }),
  createProduct({
    id: "new-series-042",
    slug: "new-series-blue-teardrop-hair-stick",
    name: "The Blue Sun - Hair Stick",
    kind: "hair accessory",
    price: 42.99,
    detailCount: 0,
    description: "The Blue Sun - Hair Stick sets a round blue center within a small radiating frame on a dark wood-toned stick, with pearl-like drops trailing from one side. Open channels around the center give the ornament a sunburst outline, while the long body turns the shape into a directional hair line. An updo with a loose twist shows the full piece; cream and navy make the blue easier to notice.",
  }),
  createProduct({
    id: "new-series-043",
    slug: "new-series-dragonfly-hair-clip",
    name: "The Jade Dragonfly - Hair Clip",
    kind: "hair accessory",
    price: 43.99,
    detailCount: 0,
    description: "The Jade Dragonfly - Hair Clip depicts pale textured wings around a green oval center, with deep violet round accents and a warm gold-toned body. Wing texture, color blocks, and the horizontal clip bar make the insect outline easy to recognize in the approved image. Near a side sweep or pinned-back section, the green and violet colors can sit against a simple neutral top.",
  }),
];
