import type { Product } from "@/lib/1688-products";

type NewSeriesProductInput = {
  id: string;
  slug: string;
  name: string;
  kind:
    | "earring design"
    | "bracelet"
    | "necklace"
    | "eyewear chain"
    | "hair accessory";
  price: number;
  detailCount: number;
  description: string;
};

function sourceGallery(slug: string, detailCount: number): string[] {
  const root = `/images/products/new-series/${slug}`;
  return [
    `${root}/main.jpg`,
    ...Array.from(
      { length: detailCount },
      (_, index) => `${root}/detail-${String(index + 1).padStart(2, "0")}.jpg`,
    ),
  ];
}

function createProduct(input: NewSeriesProductInput): Product {
  const sourceImages = sourceGallery(input.slug, input.detailCount);
  const editorialImages = [
    "new-series-white-shell-flower-drops", "new-series-gold-shell-teardrops",
    "new-series-baroque-pearl-hoops", "new-series-purple-gem-pearl-drops",
    "new-series-white-petal-flower-earrings", "new-series-mother-of-pearl-cluster-earrings",
    "new-series-white-shell-triple-drops", "new-series-round-shell-disc-drops",
    "new-series-pearl-jade-bracelet", "new-series-purple-gem-bangle",
    "new-series-shell-twist-pearl-cuff", "new-series-leaf-turquoise-pearl-cuff",
    "new-series-leaf-pearl-bracelet", "new-series-round-shell-gold-cuff",
    "new-series-purple-stone-pendant-necklace", "new-series-pearl-y-lariat",
    "new-series-green-layered-pendant-necklace", "new-series-pearl-dreamcatcher-lariat",
    "new-series-pearl-drop-choker", "new-series-multi-strand-pearl-choker",
    "new-series-black-drop-pearl-choker", "new-series-pearl-glasses-chain",
    "new-series-shell-drop-glasses-chain", "new-series-classic-pearl-chain",
    "new-series-turquoise-bead-chain",
    "new-series-white-floral-hair-stick", "new-series-white-flower-wood-stick",
    "new-series-pearl-cluster-hair-claw", "new-series-gold-pearl-hair-stick",
    "new-series-pearl-flower-u-pin", "new-series-pearl-bar-hair-clip",
    "new-series-shell-chip-hair-clip", "new-series-wood-flower-hair-stick",
    "new-series-daisy-chain-hair-stick", "new-series-wood-pearl-hair-stick",
    "new-series-gold-star-hair-stick", "new-series-star-flower-hair-clip",
    "new-series-chain-flower-hair-pin", "new-series-flower-pearl-hair-clip",
    "new-series-pink-flower-hair-clip", "new-series-blue-flower-bow-hair-clip",
    "new-series-blue-teardrop-hair-stick", "new-series-dragonfly-hair-clip",
  ].includes(input.slug)
    ? [
        `/images/products/new-series/${input.slug}/editorial-v1-01-hero.png`,
        `/images/products/new-series/${input.slug}/editorial-v1-02-macro.png`,
        `/images/products/new-series/${input.slug}/editorial-v1-03-worn.png`,
      ]
    : undefined;
  const images = editorialImages ?? sourceImages;
  const productType = input.kind === "earring design" ? "earrings" : input.kind;

  return {
    id: input.id,
    slug: input.slug,
    name: input.name,
    category: "pearl-series",
    categoryName: "The Pearl Edit",
    description: input.description,
    price: input.price,
    image: images[0],
    images,
    imageRoles: {
      primary: images[0],
      ...(images[1] ? { detail: images[1] } : {}),
      ...(images[2] ? { wearing: images[2] } : {}),
    },
    tag: "New",
    isBestSeller: false,
    isNew: true,
    isActive: true,
    inStock: true,
    rating: 0,
    reviewCount: 0,
    intention: `Pearl ${productType}`,
    benefitTriplet: "Pearl - Detail - Everyday",
  };
}

export const NEW_SERIES_PRODUCTS: Product[] = [
  createProduct({
    id: "new-series-001",
    slug: "new-series-white-shell-flower-drops",
    name: "The Dewflower - Earrings",
    kind: "earring design",
    price: 34.99,
    detailCount: 4,
    description: "The Dewflower - Earrings pair translucent white flower drops with a softly rounded center and small pale bead accents. Fine gold-toned lines give the petal silhouette a light, airy finish, while the two-level drop adds movement around the face. Let the floral shape lead with a simple blouse, or echo it with a soft ivory dress for a quiet garden note.",
  }),
  createProduct({
    id: "new-series-002",
    slug: "new-series-gold-shell-teardrops",
    name: "The Golden Petal - Earrings",
    kind: "earring design",
    price: 39.99,
    detailCount: 4,
    description: "The Golden Petal - Earrings frame a pale, petal-shaped center with rows of small cream beads and a warm gold-toned oval rim. The teardrop profile reads polished and graphic in the close-up while keeping a soft, luminous palette. Style them with an open neckline or a clean knit so the oval drop becomes the outfit's warm focal point.",
  }),
  createProduct({
    id: "new-series-003",
    slug: "new-series-baroque-pearl-hoops",
    name: "The Baroque Orbit - Earrings",
    kind: "earring design",
    price: 44.99,
    detailCount: 6,
    description: "The Baroque Orbit - Earrings contrast irregular luminous white drops with smooth round hoop forms. Each drop has a fluid, one-of-a-kind-looking outline, so the pair feels organic rather than perfectly geometric. Wear them with pulled-back hair and a crisp shirt when you want the sculptural silhouette to carry the look, or soften it with a draped neutral top.",
  }),
  createProduct({
    id: "new-series-004",
    slug: "new-series-purple-gem-pearl-drops",
    name: "The Violet Rain - Earrings",
    kind: "earring design",
    price: 42.99,
    detailCount: 4,
    description: "The Violet Rain - Earrings set a milky oval center inside a saturated violet frame scattered with bright reflective accents. A matching round stud repeats the color above the drop, creating a clear top-to-bottom rhythm. They work as a statement with monochrome black or cream, and can bring a jewel-toned spark to a simple evening outfit.",
  }),
  createProduct({
    id: "new-series-005",
    slug: "new-series-white-petal-flower-earrings",
    name: "The White Garden - Earrings",
    kind: "earring design",
    price: 39.99,
    detailCount: 4,
    description: "The White Garden - Earrings use four rounded white petal shapes around a small luminous bead, creating a clean floral silhouette with a gentle asymmetry. The pale surface catches the light without needing a busy setting. Pair them with a low bun and a soft shirt collar for a fresh daytime look, or let the simple flower brighten a darker dress.",
  }),
  createProduct({
    id: "new-series-006",
    slug: "new-series-mother-of-pearl-cluster-earrings",
    name: "The Shell Bloom - Earrings",
    kind: "earring design",
    price: 44.99,
    detailCount: 5,
    description: "The Shell Bloom - Earrings gather overlapping pearly petal forms into a full cluster, with a small bead grouping at the top and a delicate round charm below. Their layered silhouette has a soft, botanical presence in the gallery. Keep the rest of the outfit pared back, then use the cluster as the single floral accent against linen-look neutrals or a sleek black top.",
  }),
  createProduct({
    id: "new-series-007",
    slug: "new-series-white-shell-triple-drops",
    name: "The Triple Light - Earrings",
    kind: "earring design",
    price: 42.99,
    detailCount: 4,
    description: "The Triple Light - Earrings arrange three pale round shell-like discs in a descending line, each outlined by a warm gold-toned edge. The repeated circular rhythm makes the drop easy to read from the front, while the milky surface keeps it gentle. Wear them with a swept-back hairstyle and a narrow neckline to emphasize the vertical line, or pair with denim for contrast.",
  }),
  createProduct({
    id: "new-series-008",
    slug: "new-series-round-shell-disc-drops",
    name: "The Moon Disc - Earrings",
    kind: "earring design",
    price: 46.99,
    detailCount: 8,
    description: "The Moon Disc - Earrings combine dark green-gray round discs with softly iridescent lower discs and small pale bead clusters at the joins. The changing surface color gives the pair a moody, atmospheric feel without relying on a complicated silhouette. Style them with a neutral monochrome look, or use the green and blush tones to bridge a printed scarf.",
  }),
  createProduct({
    id: "new-series-009",
    slug: "new-series-pearl-jade-bracelet",
    name: "The Green Current - Bracelet",
    kind: "bracelet",
    price: 44.99,
    detailCount: 4,
    description: "The Green Current - Bracelet follows a softly irregular line of pearl-like white beads toward a smooth jade-colored oval accent. Warm gold-toned links and the contrasting green center give the wrist a calm, natural rhythm. Wear it alone with rolled sleeves when you want the center color to stand out, or layer it beside a plain chain for a more collected look.",
  }),
  createProduct({
    id: "new-series-010",
    slug: "new-series-purple-gem-bangle",
    name: "The Violet Arc - Bracelet",
    kind: "bracelet",
    price: 49.99,
    detailCount: 5,
    description: "The Violet Arc - Bracelet places a faceted purple center between pale round accents in a warm gold-toned open bangle. The straight arc keeps the silhouette clean while the violet focal point adds depth and color. Let it anchor a neutral sleeve, or repeat the purple with a small bag or scarf when dressing for an evening plan.",
  }),
  createProduct({
    id: "new-series-011",
    slug: "new-series-shell-twist-pearl-cuff",
    name: "The Shell Twist - Bracelet",
    kind: "bracelet",
    price: 46.99,
    detailCount: 5,
    description: "The Shell Twist - Bracelet wraps a twisted gold-toned line around smooth pale round forms and one irregular shell-like accent. The coiled texture creates a tactile visual contrast against the quiet white surfaces, giving the cuff an organic twist. Style it with a short sleeve so the open shape can be seen, or pair it with a simple watch for a mixed-texture stack.",
  }),
  createProduct({
    id: "new-series-012",
    slug: "new-series-leaf-turquoise-pearl-cuff",
    name: "The Turquoise Leaf - Bracelet",
    kind: "bracelet",
    price: 48.99,
    detailCount: 2,
    description: "The Turquoise Leaf - Bracelet balances two turquoise-colored round accents and a pale irregular centerpiece within a looping gold-toned frame. The leaf-like sweep across the middle gives the cuff a directional shape rather than a plain band. Wear it with cream, denim, or warm brown tones to let the blue-green color read clearly, and keep nearby jewelry minimal.",
  }),
  createProduct({
    id: "new-series-013",
    slug: "new-series-leaf-pearl-bracelet",
    name: "The Leaf Line - Bracelet",
    kind: "bracelet",
    price: 49.99,
    detailCount: 4,
    description: "The Leaf Line - Bracelet alternates pearl-like white beads with airy leaf-shaped gold-toned forms, creating a repeating rhythm around the wrist. Rounded centers soften the linear framework, while the open leaf outlines add movement in the close-up. Pair it with a flowing blouse for a botanical mood, or use it as the delicate detail against a tailored jacket.",
  }),
  createProduct({
    id: "new-series-014",
    slug: "new-series-round-shell-gold-cuff",
    name: "The Golden Shell - Bracelet",
    kind: "bracelet",
    price: 54.99,
    detailCount: 6,
    description: "The Golden Shell - Bracelet traces a chain of pearl-like beads through several sculpted leaf or shell-shaped forms, with warm gold-toned lines enclosing the pale centers. Its repeating motifs make the bracelet feel like a small botanical drawing across the wrist. Wear it as the main accent with a simple sleeve, or coordinate it with ivory and sand tones for a tonal look.",
  }),
  createProduct({
    id: "new-series-015",
    slug: "new-series-purple-stone-pendant-necklace",
    name: "The Violet Pendant - Necklace",
    kind: "necklace",
    price: 54.99,
    detailCount: 5,
    description: "The Violet Pendant - Necklace combines a faceted purple stone-like center with a strand of alternating dark, mauve, and smoky beads. A rounded gold-toned frame and ornate connector give the pendant a strong, centered finish. Let it sit over a plain crew neck so the color story stays visible, or echo one of the muted bead tones in a layered outfit.",
  }),
  createProduct({
    id: "new-series-016",
    slug: "new-series-pearl-y-lariat",
    name: "The Falling Pearl - Lariat",
    kind: "necklace",
    price: 59.99,
    detailCount: 2,
    description: "The Falling Pearl - Lariat uses a fine gold-toned chain with graduated pearl-like beads that descend from a small openwork centerpiece to a final round drop. Its Y-shaped line draws the eye downward and gives a clean neckline a little movement. Wear it over a solid scoop neck, or let the long drop peek through an open blazer for an elongated styling line.",
  }),
  createProduct({
    id: "new-series-017",
    slug: "new-series-green-layered-pendant-necklace",
    name: "The Green Layer - Necklace",
    kind: "necklace",
    price: 56.99,
    detailCount: 1,
    description: "The Green Layer - Necklace builds a symmetrical line from alternating small and larger pearl-like beads, joined by a delicate central openwork link and a long pendant drop. The layered spacing keeps the design airy while the warm cream palette stays easy to coordinate. Pair it with an open collar for a defined focal point, or wear it over a fine knit for a softer contrast.",
  }),
  createProduct({
    id: "new-series-018",
    slug: "new-series-pearl-dreamcatcher-lariat",
    name: "The Dreamcatcher Pearl - Lariat",
    kind: "necklace",
    price: 62.99,
    detailCount: 1,
    description: "The Dreamcatcher Pearl - Lariat keeps a fine chain quiet at the neckline, then gathers pearl-like beads around a small openwork medallion before extending into a long drop. The balanced upper line and trailing center create a graceful lariat silhouette. Style it with a clean V-neck or an open shirt, letting the pendant shape the space without adding another necklace.",
  }),
  createProduct({
    id: "new-series-019",
    slug: "new-series-pearl-drop-choker",
    name: "The Pearl Drop - Choker",
    kind: "necklace",
    price: 57.99,
    detailCount: 3,
    description: "The Pearl Drop - Choker follows the neck with a close line of small pearl-like beads and adds several slim chain drops along the front edge. The repeated drops create a fringe effect that moves the eye across the collar line. Keep your neckline simple so the detail remains legible, or pair it with a low bun and a dark top for a crisp light-on-dark contrast.",
  }),
  createProduct({
    id: "new-series-020",
    slug: "new-series-multi-strand-pearl-choker",
    name: "The Pearl Cascade - Choker",
    kind: "necklace",
    price: 64.99,
    detailCount: 2,
    description: "The Pearl Cascade - Choker pairs a fine gold-toned chain with many hanging strands of pearl-like beads arranged in a soft cascade. The asymmetrical lengths give the neckline a sense of motion while the repeated pale accents keep the palette cohesive. Wear it with a square or open neckline when you want the cascade visible, and keep earrings small so the layers have room to speak.",
  }),
  createProduct({
    id: "new-series-021",
    slug: "new-series-black-drop-pearl-choker",
    name: "The Midnight Drop - Choker",
    kind: "necklace",
    price: 59.99,
    detailCount: 1,
    description: "The Midnight Drop - Choker brings a pale, close-set pearl-like line together with fine gold-toned chains that fall into a pointed front arrangement. The vertical fringe gives the classic collar line a more dramatic, night-time mood while keeping the palette restrained. Wear it over black or charcoal for a sharp tonal look, or use a white shirt to make the center line stand out.",
  }),
  createProduct({
    id: "new-series-022",
    slug: "new-series-pearl-glasses-chain",
    name: "The Pearl Line - Eyewear Chain",
    kind: "eyewear chain",
    price: 34.99,
    detailCount: 4,
    description: "The Pearl Line - Eyewear Chain strings rounded pearl-like beads at measured intervals along a fine gold-toned chain, with clear loops at each end for glasses. The long, quiet line keeps the accessory easy to read while adding a soft point of light near the shoulders. Use it with clear or metal frames when you want the chain to blend in, or let it contrast with dark frames.",
  }),
  createProduct({
    id: "new-series-023",
    slug: "new-series-shell-drop-glasses-chain",
    name: "The Shell Drop - Eyewear Chain",
    kind: "eyewear chain",
    price: 36.99,
    detailCount: 2,
    description: "The Shell Drop - Eyewear Chain anchors each end with a small fan-shaped shell-like pendant on a slim gold-toned chain. The scalloped drop gives a functional glasses chain a distinct coastal-inspired accent without overwhelming the frame. Pair it with simple sunglasses for a noticeable finish, or choose light-colored frames so the pale pendants and warm chain stay in balance.",
  }),
  createProduct({
    id: "new-series-024",
    slug: "new-series-classic-pearl-chain",
    name: "The Classic Pearl - Eyewear Chain",
    kind: "eyewear chain",
    price: 32.99,
    detailCount: 0,
    description: "The Classic Pearl - Eyewear Chain keeps a slim gold-toned line understated with evenly spaced pearl-like beads through the front sections and clear glasses loops at both ends. Its restrained rhythm can sit behind the neck or fall along the shoulders without competing with the frames. Wear it with everyday optical frames, or use it to soften a structured blazer and button-down.",
  }),
  createProduct({
    id: "new-series-025",
    slug: "new-series-turquoise-bead-chain",
    name: "The Turquoise Note - Eyewear Chain",
    kind: "eyewear chain",
    price: 34.99,
    detailCount: 0,
    description: "The Turquoise Note - Eyewear Chain adds two vertical runs of irregular turquoise-colored beads to an otherwise fine gold-toned glasses chain. The small stone-like shapes create a clear color break near the shoulders and make the accessory easy to spot from the front. Pair it with neutral frames and denim, or repeat the blue-green note in a scarf or small bag.",
  }),
  createProduct({
    id: "new-series-026",
    slug: "new-series-white-floral-hair-stick",
    name: "The Blueheart Bloom - Hair Stick",
    kind: "hair accessory",
    price: 36.99,
    detailCount: 0,
    description: "The Blueheart Bloom - Hair Stick centers a white, many-petaled flower on a slim gold-toned stick, with a cool blue-green round center that gives the pale bloom a fresh point of color. The long line reads cleanly against the floral top. Use it to finish a low twist or loose updo, and let the blue center echo a cool-toned blouse.",
  }),
  createProduct({
    id: "new-series-027",
    slug: "new-series-white-flower-wood-stick",
    name: "The Ivory Woodflower - Hair Stick",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Ivory Woodflower - Hair Stick combines a dark wood-toned curved stick with a small white flower and a pearl-like hanging accent. The warm brown base grounds the pale floral detail, creating an organic contrast between the long line and the rounded ornament. Slide it through a loose bun for a relaxed finish, or pair it with cream and brown layers for a tonal look.",
  }),
  createProduct({
    id: "new-series-028",
    slug: "new-series-pearl-cluster-hair-claw",
    name: "The Pearl Cluster - Hair Claw",
    kind: "hair accessory",
    price: 42.99,
    detailCount: 0,
    description: "The Pearl Cluster - Hair Claw gathers irregular white pearl-like forms into a full floral cluster around a rounded center, with a visible gold-toned claw base behind it. Its dense top becomes a clear focal point even when the hair is styled simply. Use it to lift a low twist or hold a side section, and keep other hair accessories quiet so the cluster remains the detail.",
  }),
  createProduct({
    id: "new-series-029",
    slug: "new-series-gold-pearl-hair-stick",
    name: "The Golden Pearl - Hair Stick",
    kind: "hair accessory",
    price: 34.99,
    detailCount: 0,
    description: "The Golden Pearl - Hair Stick uses a long, slim gold-toned line topped by one luminous elongated pearl-like accent and a small open floral connector. The simple vertical profile gives the ornament a refined, uncluttered finish. Slide it into a smooth bun for a polished line, or use it with softly pinned hair when you want the pale accent to catch the light.",
  }),
  createProduct({
    id: "new-series-030",
    slug: "new-series-pearl-flower-u-pin",
    name: "The Pearl Halo - U Pin",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Pearl Halo - U Pin places a five-petal flower and rounded pearl-like center inside a circular halo of small pale accents, then extends into two long prongs. The open ring gives the piece a clear frame and a little negative space. Tuck it into a bun or braided updo as the finishing point, pairing it with a plain neckline so the floral circle remains visible.",
  }),
  createProduct({
    id: "new-series-031",
    slug: "new-series-pearl-bar-hair-clip",
    name: "The Triple Bloom - Hair Clip",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Triple Bloom - Hair Clip brings three flower-like clusters together across a gold-toned bar, with varied pale rounded forms and a warmer center in the middle bloom. The horizontal shape reads like a small floral band rather than a single ornament. Place it above a low ponytail or across a side sweep, and choose a simple outfit when you want the three-part silhouette to carry the look.",
  }),
  createProduct({
    id: "new-series-032",
    slug: "new-series-shell-chip-hair-clip",
    name: "The Shell Petal - Hair Clip",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Shell Petal - Hair Clip arranges irregular pale shell-like pieces and small rounded bead accents over an open gold-toned filigree base. Its asymmetrical petal shapes give the clip a gathered, beach-inspired feel while the warm outline keeps the composition defined. Use it to pin one side of the hair or finish a loose half-up style, then echo the pale tones in your outfit.",
  }),
  createProduct({
    id: "new-series-033",
    slug: "new-series-wood-flower-hair-stick",
    name: "The Woodflower Pearl - Hair Stick",
    kind: "hair accessory",
    price: 37.99,
    detailCount: 0,
    description: "The Woodflower Pearl - Hair Stick pairs a dark wood-toned stick with two small floral ornaments and a single pale drop, creating a gentle contrast between the long curved base and the light details. The shape feels botanical without becoming overly ornate. Wear it through a low bun or twist, and let the brown base complement warm neutrals, denim, or natural textures.",
  }),
  createProduct({
    id: "new-series-034",
    slug: "new-series-daisy-chain-hair-stick",
    name: "The Daisy Chain - Hair Stick",
    kind: "hair accessory",
    price: 36.99,
    detailCount: 0,
    description: "The Daisy Chain - Hair Stick turns a pale daisy-like flower into a playful hair accent with a bright yellow center, pearl-like petal forms, and two trailing gold-toned chains. The long stick keeps the silhouette directional while the chains add movement beside the updo. Use it in a loose bun or braid, especially with cream, yellow, or denim accents elsewhere in the look.",
  }),
  createProduct({
    id: "new-series-035",
    slug: "new-series-wood-pearl-hair-stick",
    name: "The Cloud Pearl - Hair Stick",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Cloud Pearl - Hair Stick uses a dark openwork stick with a rounded top and three pearl-like drops suspended from fine gold-toned chains. The airy cut-outs keep the long silhouette from feeling heavy, while the pale drops create a gentle trailing detail. Slide it through a bun or twist, and pair it with soft neutrals for a calm, graphic finish.",
  }),
  createProduct({
    id: "new-series-036",
    slug: "new-series-gold-star-hair-stick",
    name: "The Amber Bloom - U Pin",
    kind: "hair accessory",
    price: 41.99,
    detailCount: 0,
    description: "The Amber Bloom - U Pin combines a white five-petal flower, a warm amber-colored center, and small branch-like details above a long double-prong base. The bright center gives the pale bloom a sunny focal point, while the open prongs keep the profile clear. Use it to anchor a bun or chignon, and repeat the amber tone with a warm scarf or understated makeup.",
  }),
  createProduct({
    id: "new-series-037",
    slug: "new-series-star-flower-hair-clip",
    name: "The Pink Pearl Star - Hair Clip",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Pink Pearl Star - Hair Clip brings a pale star-shaped flower to a gold-toned bar, with a soft pink rounded center and small bright accents around it. The pointed petals give the clip a crisp outline, while the center keeps it romantic. Wear it on a side sweep or at the base of a ponytail, and let the pink tone stand against cream, navy, or washed denim.",
  }),
  createProduct({
    id: "new-series-038",
    slug: "new-series-chain-flower-hair-pin",
    name: "The Pearl Canopy - U Pin",
    kind: "hair accessory",
    price: 44.99,
    detailCount: 0,
    description: "The Pearl Canopy - U Pin combines a small cluster of rounded pearl-like forms with an open rectangular frame and several fine gold-toned chains that hang below it. The mix of fixed and moving lines creates a canopy-like profile with a clear vertical direction. Tuck it into a bun or braided style when you want a little ceremony, keeping the neckline clean.",
  }),
  createProduct({
    id: "new-series-039",
    slug: "new-series-flower-pearl-hair-clip",
    name: "The Pearl Moth - Hair Clip",
    kind: "hair accessory",
    price: 39.99,
    detailCount: 0,
    description: "The Pearl Moth - Hair Clip uses a warm gold-toned bar as the base for an organic cluster of pale, irregular pearl-like forms, including a darker rounded accent that gives the center depth. The wing-like arrangement feels playful and sculptural without needing extra ornament. Pin it at the temple or on a low twist, and let the shape contrast with a dark top.",
  }),
  createProduct({
    id: "new-series-040",
    slug: "new-series-pink-flower-hair-clip",
    name: "The Blush Cluster - Hair Clip",
    kind: "hair accessory",
    price: 36.99,
    detailCount: 0,
    description: "The Blush Cluster - Hair Clip gathers soft pink and white rounded forms into a compact floral grouping on a slim gold-toned clip. Its close arrangement creates a small, concentrated point of color that can brighten a simple hairstyle. Place it above one ear or at the side of a low ponytail, pairing it with cream, blush, or warm beige for a gentle palette.",
  }),
  createProduct({
    id: "new-series-041",
    slug: "new-series-blue-flower-bow-hair-clip",
    name: "The Sea Glass Bloom - Hair Clip",
    kind: "hair accessory",
    price: 38.99,
    detailCount: 0,
    description: "The Sea Glass Bloom - Hair Clip centers a cool blue-green rounded accent inside a cluster of pale petal-like forms on a warm gold-toned bar. The contrast between the watery center and luminous petals gives the clip a fresh, coastal color story. Use it to finish a side sweep or half-up style, and repeat the blue-green note with denim or a cool-toned knit.",
  }),
  createProduct({
    id: "new-series-042",
    slug: "new-series-blue-teardrop-hair-stick",
    name: "The Blue Sun - Hair Stick",
    kind: "hair accessory",
    price: 42.99,
    detailCount: 0,
    description: "The Blue Sun - Hair Stick sets a round blue center inside a small radiating frame on a dark wood-toned stick, with a line of pearl-like drops trailing from one side. The sunburst shape and open channels give the long piece a graphic, directional feel. Slide it through a bun or twist, and pair it with cream, navy, or other cool neutrals.",
  }),
  createProduct({
    id: "new-series-043",
    slug: "new-series-dragonfly-hair-clip",
    name: "The Jade Dragonfly - Hair Clip",
    kind: "hair accessory",
    price: 43.99,
    detailCount: 0,
    description: "The Jade Dragonfly - Hair Clip captures a dragonfly silhouette with pale, textured wings, a green oval center, deep violet round accents, and a warm gold-toned body. The mix of jewel-like color and wing texture makes it a distinctive focal point. Wear it on a side sweep or pinned-back section, using a simple hairstyle and letting the green and violet accents provide the contrast.",
  }),
];
